#!/bin/bash
echo "========================================"
echo "FLUTTER-CONTROL HOST DIAGNOSTIC REPORT"
echo "========================================"
echo "Date: $(date)"
echo "Hostname: $(hostname)"
echo ""

echo "========================================"
echo "1. LAUNCHAGENTS"
echo "========================================"
echo "--- Loaded LaunchAgents (flutter/android/erace) ---"
launchctl list | grep -E "flutter|android|erace" || echo "(none found)"
echo ""
echo "--- LaunchAgent plist files ---"
ls -la ~/Library/LaunchAgents/*flutter* ~/Library/LaunchAgents/*android* ~/Library/LaunchAgents/*erace* 2>/dev/null || echo "(none found)"
echo ""
echo "--- Contents of flutter-control plist files ---"
cat ~/Library/LaunchAgents/com.erace.flutter-control.plist 2>/dev/null && echo ""
cat ~/Library/LaunchAgents/com.erace.flutter-control.android.plist 2>/dev/null && echo ""
cat ~/Library/LaunchAgents/com.erace.flutter-control.ios.plist 2>/dev/null && echo ""
cat ~/Library/LaunchAgents/com.erace.flutter-control.observatory-bridge.plist 2>/dev/null && echo ""

echo "========================================"
echo "2. LISTENING PORTS"
echo "========================================"
echo "--- Ports 9225, 9226, 9227, 15037 ---"
lsof -i :9225 -i :9226 -i :9227 -i :15037 2>/dev/null || echo "(none listening)"
echo ""

echo "========================================"
echo "3. SERVICE HEALTH CHECKS"
echo "========================================"
echo "--- Port 9225 (Android) ---"
curl -s http://localhost:9225/health 2>&1 || echo "Not responding"
curl -s http://localhost:9225/version 2>&1 || echo "No version"
echo ""
echo "--- Port 9226 (iOS VM - should not respond from host) ---"
curl -s --connect-timeout 2 http://localhost:9226/health 2>&1 || echo "Not responding (expected)"
echo ""
echo "--- Port 9227 (iOS Host) ---"
curl -s http://localhost:9227/health 2>&1 || echo "Not responding"
curl -s http://localhost:9227/version 2>&1 || echo "No version"
echo ""

echo "========================================"
echo "4. FLUTTER-CONTROL INSTALLATION"
echo "========================================"
echo "--- Venv location ---"
ls -la ~/.flutter-control-venv/bin/flutter-control* 2>/dev/null || echo "(not found)"
echo ""
echo "--- Installed version ---"
~/.flutter-control-venv/bin/python3 -c "from flutter_control import __version__; print(f'Version: {__version__}')" 2>&1 || echo "(cannot determine)"
echo ""

echo "========================================"
echo "5. PROCESS LIST"
echo "========================================"
echo "--- Flutter-control processes ---"
ps aux | grep -E "flutter.control|flutter-control" | grep -v grep || echo "(none running)"
echo ""

echo "========================================"
echo "6. MAESTRO STATUS"
echo "========================================"
echo "--- Maestro version ---"
~/.maestro/bin/maestro --version 2>&1 || echo "(not installed)"
echo ""
echo "--- Port 7001 forwarding ---"
adb forward --list 2>&1 | grep 7001 || echo "(7001 not forwarded)"
echo ""

echo "========================================"
echo "7. ADB STATUS"
echo "========================================"
echo "--- ADB devices ---"
adb devices 2>&1
echo ""
echo "--- ADB forward list ---"
adb forward --list 2>&1
echo ""

echo "========================================"
echo "8. LOGS (last 20 lines)"
echo "========================================"
echo "--- Android stderr.log ---"
tail -20 ~/Library/Logs/flutter-control/stderr.log 2>/dev/null || echo "(no log)"
echo ""
echo "--- iOS stderr.log (if separate) ---"
tail -20 ~/Library/Logs/flutter-control-ios/stderr.log 2>/dev/null || echo "(no separate iOS log)"
echo ""

echo "========================================"
echo "9. ENVIRONMENT"
echo "========================================"
echo "--- Relevant env vars ---"
env | grep -E "FLUTTER|ANDROID|ADB|MCP" || echo "(none set)"
echo ""

echo "========================================"
echo "10. IOS SIMULATORS"
echo "========================================"
echo "--- Booted simulators ---"
xcrun simctl list devices booted 2>&1 || echo "(cannot list)"
echo ""

echo "========================================"
echo "END OF DIAGNOSTIC REPORT"
echo "========================================"
